# Generated by Django 5.0.7 on 2024-07-29 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='fone',
            new_name='phone',
        ),
    ]
